### ISSUE TITLE
Wrong statistics shown

### ISSUE THREAD

**Issue by naiii** [RedFantom/GSF-Parser-Public#2]
This error can be replicated:

1.- Open combat log
2.- select match (right stats are shown)
3.- Select: File->Open statistics file->Cancel (error msg "This file could not be opened", itself is an error, I didn't open any file, I canceled the action)
4.- Select match (now it shows some other stats, and are the same for any match)

**Comment by RedFantom** [comment]
While the openCombatLog() function exited when a file could not opened, the openStatisticsFile() did not. I changed that by adding "return -1" after the exception occurred. I have also removed the message boxes because they were indeed annoying. When a non-existent file is selected in the dialog-prompt, there is a lot more going on than just this program ;) .
